#/usr/bin/env sh

ZLIB_VERSION=1.2.8
LIBZIP_VERSION=1.1.3
LIBELF_VERSION=0.8.13
JANSSON_VERSION=2.8
DLFCN_VERSION=1.0.0
BINUTILS_VERSION=2.25.1
GCC_VERSION=4.9.4

JOBS=-j4

ROOTDIR=$(pwd)
PATCHDIR=$(pwd)/patch
DOWNLOADDIR=${ROOTDIR}/download
SRCDIR=${ROOTDIR}/src
BUILDDIR=${ROOTDIR}/build
SRCRELDIR=$(realpath --relative-to="${BUILDDIR}" ${SRCDIR})
INSTALLDIR=${ROOTDIR}/install
VITASDKROOT=${ROOTDIR}/vitasdk
